# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4b9327d5bffdd8d669ef24eea7444fe19440c2e2cd98b618b2d21a2407818ac87b12863a9838fb8b656b2902de426a7b1931316240a1e43c1f5627561596f0f

test:
  secret_key_base: 8f00008af966b760e7b9cfd93aab50ce8c78fe386be866c32b2c5207ed4af7e3169090c6f2ac042d828e22544661217793e89bf250435f4d9e0736e6efdfb1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
